version: '3.5'

services:
  dsb-web-server:
    container_name: dsb-web-server
    build:
      context: ./docker/server
      args:
        UID: $U_ID
    ports:
      - 8084:80
    volumes:
      - ./public:/appdata/www/public
    networks:
      - dsb-network
  
  dsb-php:
    container_name: dsb-php
    build:
      context: ./docker/php
      args:
        UID: $U_ID
    volumes:
      - ./:/appdata/www
    networks:
      - dsb-network
  
  dsb-db:
    container_name: dsb-db
    image: mysql:8.0
    labels:
      "instance-name": "docker-symfony-base-mysql-8.0"
    ports:
      - 40102:3306
    environment:
      MYSQL_DATABASE: dsb_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --sql_mode="STRICT_ALL_TABLES,NO_ENGINE_SUBSTITUTION"
    volumes:
      - ./dsb-database-data:/var/lib/mysql
    networks:
      - dsb-network

networks:
  dsb-network:
    external: true
